### ISSUE TITLE
Preparation for the release of PHP 8

### ISSUE THREAD

**Issue by MarkBaker** [PHPOffice/PhpSpreadsheet#1552]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Travis template needs updating to run against PHP 8 nightly builds once it reaches a stable point (feature freeze) so that we know all functionality will still work with the new version.  Initially this should be an "allow fail", giving us a chance to resolve any issues that may be identified without breaking the build.

Also requires updates to composer.json and related dependencies to ensure that they are all at appropriate versions for running with PHP 8.

**Comment by flavioheleno** [comment]
If you don't mind, I'd like to give it a shot. :-)

**Comment by flavioheleno** [comment]
Tasks:
- [ ] Update `.travis.yml` to include `nightly`
- [ ] Update `composer.json` PHP requirement to `^7.2 || ^8.0`
- [ ] Update  `markbaker/complex` to `^2.0`
- [ ] Update `markbaker/matrix` to `^2.0`
- [ ] Update `phpunit/phpunit` to `^9.3`

Pending:
- [ ] Wait for `dompdf/dompdf` to support PHP8 ([dompdf/dompdf#2242](https://github.com/dompdf/dompdf/issues/2242))
- [ ] Wait for `friendsofphp/php-cs-fixer` to support PHP8 ([friendsofphp/php-cs-fixer#4702](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702))
- [ ] Wait for `mpdf/mpdf` to support PHP8 ([mpdf/mpdf#1263](https://github.com/mpdf/mpdf/issues/1263))

**Comment by MarkBaker** [comment]
Currently all tests passing (pdf tests are skipped until those libraries are version ready to run under PHP8)... biggest problem is `tcPDF`, which is no longer supported, and its successor library `tc-lib-pdf` is still "under development", and not yet ready for release. Surprisingly, mPDF still runs against PHP8 without any issues; but we may need to change recommendations or the PDF adaptors later as these libraries are modified for PHP8

**Comment by MarkBaker** [comment]
Next phase of this work is assessing the argument names in public methods to ensure that they are appropriate and meaningful for use as PHP8 named arguments

**Comment by misterakko** [comment]
Hope this helps... I see this when running PHP 8.0.0

Fatal error: Uncaught TypeError: Unsupported operand types: string % int in PhpSpreadsheet/Cell/Coordinate.php:302 Stack trace: #0 PhpSpreadsheet/Worksheet/Worksheet.php(1518): PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex() #1 /var/www/sarat1230b2/sar-el_utilities.inc.php(299): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->getStyleByColumnAndRow() #2 /var/www/sarat1230b2/masterUsers.php(72): QueryAndExport() #3 {main} thrown in PhpSpreadsheet/Cell/Coordinate.php on line 302

**Comment by keradus** [comment]
you can now update PHP CS Fixer to v2.18+ that supports v8

**Comment by ccimmo** [comment]
". Surprisingly, mPDF still runs against PHP8 without any issues; but we may need to change recommendations or the PDF adaptors later as these libraries are modified for PHP8"

Mpdf does not write drawings/charts... phpspreadsheet output the right excel sheet with all drawing (writer\xlsx) but when running new \Phpoffice\phpspreadsheet\Writer\Pdf\Mpdf, the pdf is created without drawings...
